dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-7
      - ubuntu-toolchain-r-test
    packages:
      - clang-7.0
      - gcc-7

before_script:
  - git submodule update --init --recursive

script: |
  make -e clean && \
  CXX=/usr/bin/clang++-7.0 CC=/usr/bin/clang-7.0 make -e && \
  CXX=/usr/bin/clang++-7.0 CC=/usr/bin/clang-7.0 make -e test && \
  make -e clean && \
  CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 make -e && \
  CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 make -e test
